// Muscle group data — keyed by id used in body.js mesh userData.
export const MUSCLES = {
  traps: {
    name: 'Trapezius',
    latin: 'Musculus trapezius',
    region: 'Neck & upper back',
    desc: 'A large, kite-shaped muscle spanning from the base of the skull down the middle of the back and out to the shoulder blades.',
    fn: 'Elevates, retracts, and depresses the scapula; supports the arm and extends the neck.',
    exercises: ['Shrugs', 'Face pulls', 'Deadlifts', 'Farmer carries'],
  },
  delts: {
    name: 'Deltoids',
    latin: 'Musculus deltoideus',
    region: 'Shoulder',
    desc: 'The rounded cap of the shoulder, made of three heads — anterior, lateral, and posterior — that wrap the shoulder joint.',
    fn: 'Abducts the arm; the front head flexes and internally rotates it, the rear head extends and externally rotates it.',
    exercises: ['Overhead press', 'Lateral raises', 'Rear-delt flyes'],
  },
  pecs: {
    name: 'Pectorals',
    latin: 'Pectoralis major',
    region: 'Chest',
    desc: 'The broad, fan-shaped muscle of the chest, running from the sternum and collarbone to the upper arm.',
    fn: 'Adducts and internally rotates the arm; presses the arms forward and together.',
    exercises: ['Bench press', 'Push-ups', 'Dumbbell flyes', 'Dips'],
  },
  biceps: {
    name: 'Biceps',
    latin: 'Biceps brachii',
    region: 'Front upper arm',
    desc: 'The two-headed muscle on the front of the upper arm, crossing both the shoulder and elbow joints.',
    fn: 'Flexes the elbow and supinates the forearm — turning the palm upward.',
    exercises: ['Barbell curls', 'Chin-ups', 'Hammer curls'],
  },
  triceps: {
    name: 'Triceps',
    latin: 'Triceps brachii',
    region: 'Back upper arm',
    desc: 'The three-headed muscle on the back of the upper arm — roughly two thirds of upper-arm mass.',
    fn: 'Extends the elbow, straightening the arm; the long head also assists shoulder extension.',
    exercises: ['Dips', 'Close-grip bench', 'Cable pushdowns', 'Skullcrushers'],
  },
  forearms: {
    name: 'Forearms',
    latin: 'Flexores & extensores antebrachii',
    region: 'Lower arm',
    desc: 'A dense bundle of nearly twenty muscles controlling the wrist, hand, and fingers.',
    fn: 'Flex and extend the wrist and fingers; drive grip strength and forearm rotation.',
    exercises: ['Wrist curls', 'Dead hangs', 'Reverse curls', 'Grippers'],
  },
  abs: {
    name: 'Abdominals',
    latin: 'Rectus abdominis',
    region: 'Core — front',
    desc: 'The paired, segmented "six-pack" muscle running vertically from ribcage to pelvis, divided by tendinous bands.',
    fn: 'Flexes the spine, compresses the abdomen, and stabilizes the trunk under load.',
    exercises: ['Hanging leg raises', 'Cable crunches', 'Ab-wheel rollouts', 'Planks'],
  },
  obliques: {
    name: 'Obliques',
    latin: 'Obliquus externus abdominis',
    region: 'Core — sides',
    desc: 'Layered sheets of muscle wrapping the sides of the waist, fibers running diagonally like crossed straps.',
    fn: 'Rotate and side-bend the trunk; brace the core against twisting forces.',
    exercises: ['Russian twists', 'Side planks', 'Woodchoppers', 'Suitcase carries'],
  },
  lats: {
    name: 'Lats',
    latin: 'Latissimus dorsi',
    region: 'Back',
    desc: 'The widest muscle of the body — broad wings sweeping from the lower spine up to the upper arm.',
    fn: 'Pulls the arm down and back; adducts, extends, and internally rotates the shoulder.',
    exercises: ['Pull-ups', 'Lat pulldowns', 'Barbell rows'],
  },
  lowback: {
    name: 'Lower back',
    latin: 'Erector spinae',
    region: 'Back — spine',
    desc: 'Long columns of muscle running either side of the spine from the pelvis to the skull.',
    fn: 'Extends and straightens the spine; keeps the torso upright and braced during lifts.',
    exercises: ['Deadlifts', 'Back extensions', 'Good mornings'],
  },
  glutes: {
    name: 'Glutes',
    latin: 'Gluteus maximus',
    region: 'Hip',
    desc: 'The largest muscle in the human body, forming the bulk of the buttock.',
    fn: 'Extends the hip — the primary driver in standing up, climbing, sprinting, and jumping.',
    exercises: ['Hip thrusts', 'Squats', 'Romanian deadlifts', 'Lunges'],
  },
  quads: {
    name: 'Quadriceps',
    latin: 'Quadriceps femoris',
    region: 'Front thigh',
    desc: 'The four-headed muscle group on the front of the thigh, converging into the patellar tendon.',
    fn: 'Extends the knee; the rectus femoris head also flexes the hip.',
    exercises: ['Squats', 'Leg press', 'Bulgarian split squats', 'Leg extensions'],
  },
  hams: {
    name: 'Hamstrings',
    latin: 'Biceps femoris, semitendinosus, semimembranosus',
    region: 'Back thigh',
    desc: 'Three long muscles down the back of the thigh, crossing both hip and knee.',
    fn: 'Flex the knee and extend the hip; decelerate the leg when sprinting.',
    exercises: ['Romanian deadlifts', 'Leg curls', 'Nordic curls'],
  },
  calves: {
    name: 'Calves',
    latin: 'Gastrocnemius & soleus',
    region: 'Lower leg',
    desc: 'The twin-bellied gastrocnemius over the deeper soleus, tapering into the Achilles tendon.',
    fn: 'Plantar-flex the ankle — pointing the foot to walk, run, and jump.',
    exercises: ['Standing calf raises', 'Seated calf raises', 'Jump rope'],
  },
};

// Display order for the sidebar list.
export const MUSCLE_ORDER = [
  'traps', 'delts', 'pecs', 'biceps', 'triceps', 'forearms',
  'abs', 'obliques', 'lats', 'lowback',
  'glutes', 'quads', 'hams', 'calves',
];
