// Muscle group data — keyed by id used in body.js mesh userData.
export const MUSCLES = {
  traps: {
    name: 'Trapezius',
    latin: 'Musculus trapezius',
    region: 'Neck & upper back',
    desc: 'A large, kite-shaped muscle spanning from the base of the skull down the middle of the back and out to the shoulder blades.',
    fn: 'Elevates, retracts, and depresses the scapula; supports the arm and extends the neck.',
    bodyweight: ['Inverted rows', 'Pike shrugs', 'Wall handstand holds'],
    weights: ['Shrugs', 'Face pulls', 'Deadlifts', 'Farmer carries'],
    sport: "Wrestlers build famously thick traps from bridging and collar ties, and the same region takes the classic 'burner' when a shoulder is driven down while the head snaps the other way. Trap and levator strains are routine after long clinch exchanges.",
  },
  delts: {
    name: 'Deltoids',
    latin: 'Musculus deltoideus',
    region: 'Shoulder',
    desc: 'The rounded cap of the shoulder, made of three heads — anterior, lateral, and posterior — that wrap the shoulder joint.',
    fn: 'Abducts the arm; the front head flexes and internally rotates it, the rear head extends and externally rotates it.',
    bodyweight: ['Pike push-ups', 'Handstand push-ups', 'Wall walks'],
    weights: ['Overhead press', 'Lateral raises', 'Rear-delt flyes'],
    sport: "The most dislocated joint in combat sport. Kimuras, americanas and armbars load it near its end range, and posting a hand on a hard takedown drives the head of the humerus forward.",
  },
  pecs: {
    name: 'Pectorals',
    latin: 'Pectoralis major',
    region: 'Chest',
    desc: 'The broad, fan-shaped muscle of the chest, running from the sternum and collarbone to the upper arm.',
    fn: 'Adducts and internally rotates the arm; presses the arms forward and together.',
    bodyweight: ['Push-ups', 'Dips', 'Archer push-ups', 'Pseudo-planche push-ups'],
    weights: ['Bench press', 'Dumbbell flyes', 'Cable crossovers'],
    sport: "Pec major tears at its insertion when the arm is forced backward against a maximal contraction — heavy bench work, defending an armbar, or a hook that misses and overextends. It shows as a tearing pop, deep bruising and a hollow at the armpit fold, and near-complete tears are usually repaired surgically.",
  },
  biceps: {
    name: 'Biceps',
    latin: 'Biceps brachii',
    region: 'Front upper arm',
    desc: 'The two-headed muscle on the front of the upper arm, crossing both the shoulder and elbow joints.',
    fn: 'Flexes the elbow and supinates the forearm — turning the palm upward.',
    bodyweight: ['Chin-ups', 'Ring curls', 'Rope climbs'],
    weights: ['Barbell curls', 'Hammer curls', 'Incline curls'],
    sport: "Distal biceps ruptures are a grappler's injury: a heavy pull on an underhook or gi grip, or resisting an armbar, against a flexed elbow. Retraction gives the 'Popeye' bulge.",
  },
  triceps: {
    name: 'Triceps',
    latin: 'Triceps brachii',
    region: 'Back upper arm',
    desc: 'The three-headed muscle on the back of the upper arm — roughly two thirds of upper-arm mass.',
    fn: 'Extends the elbow, straightening the arm; the long head also assists shoulder extension.',
    bodyweight: ['Diamond push-ups', 'Bench dips', 'Bodyweight extensions'],
    weights: ['Close-grip bench', 'Cable pushdowns', 'Skullcrushers'],
    sport: "Loaded constantly by straight punching and by posting to defend takedowns. True triceps tendon avulsion is rare, but overuse tendinopathy at the elbow is common in strikers.",
  },
  forearms: {
    name: 'Forearms',
    latin: 'Flexores & extensores antebrachii',
    region: 'Lower arm',
    desc: 'A dense bundle of nearly twenty muscles controlling the wrist, hand, and fingers.',
    fn: 'Flex and extend the wrist and fingers; drive grip strength and forearm rotation.',
    bodyweight: ['Dead hangs', 'Towel hangs', 'Fingertip push-ups'],
    weights: ['Wrist curls', 'Reverse curls', 'Grippers'],
    sport: "Gi and wrist grips cause forearm pump and medial epicondylitis; hard blocks bruise the muscle bellies directly. Grip endurance fails before the shoulders in most grappling rounds.",
  },
  abs: {
    name: 'Abdominals',
    latin: 'Rectus abdominis',
    region: 'Core — front',
    desc: 'The paired, segmented "six-pack" muscle running vertically from ribcage to pelvis, divided by tendinous bands.',
    fn: 'Flexes the spine, compresses the abdomen, and stabilizes the trunk under load.',
    bodyweight: ['Hanging leg raises', 'Planks', 'L-sits', 'Dragon flags'],
    weights: ['Cable crunches', 'Ab-wheel rollouts', 'Weighted sit-ups'],
    sport: "Braced against knees and body kicks. Rectus strains and, more painfully, tears near the rib insertion make breathing and rotation hurt for weeks.",
  },
  obliques: {
    name: 'Obliques',
    latin: 'Obliquus externus abdominis',
    region: 'Core — sides',
    desc: 'Layered sheets of muscle wrapping the sides of the waist, fibers running diagonally like crossed straps.',
    fn: 'Rotate and side-bend the trunk; brace the core against twisting forces.',
    bodyweight: ['Side planks', 'Windshield wipers', 'Hanging knee twists'],
    weights: ['Woodchoppers', 'Suitcase carries', 'Weighted Russian twists'],
    sport: "Rotational punching strains the obliques the same way pitching does. A side abdominal tear ends camps quietly because every punch and every breath loads it.",
  },
  lats: {
    name: 'Lats',
    latin: 'Latissimus dorsi',
    region: 'Back',
    desc: 'The widest muscle of the body — broad wings sweeping from the lower spine up to the upper arm.',
    fn: 'Pulls the arm down and back; adducts, extends, and internally rotates the shoulder.',
    bodyweight: ['Pull-ups', 'Australian pull-ups', 'Front lever rows'],
    weights: ['Lat pulldowns', 'Barbell rows', 'Dumbbell rows'],
    sport: "The engine of the underhook, the pull in the clinch and the finish of a throw. Strains happen when an opponent rips an arm overhead while the lat is contracting.",
  },
  lowback: {
    name: 'Lower back',
    latin: 'Erector spinae',
    region: 'Back — spine',
    desc: 'Long columns of muscle running either side of the spine from the pelvis to the skull.',
    fn: 'Extends and straightens the spine; keeps the torso upright and braced during lifts.',
    bodyweight: ['Supermans', 'Bird dogs', 'Reverse hyperextensions'],
    weights: ['Deadlifts', 'Back extensions', 'Good mornings'],
    sport: "Wrestlers and grapplers carry the highest disc-injury load in sport: repeated flexion under compression in scrambles, stacks and heavy pulls. Chronic low-back pain is the single commonest complaint in senior wrestlers.",
  },
  glutes: {
    name: 'Glutes',
    latin: 'Gluteus maximus',
    region: 'Hip',
    desc: 'The largest muscle in the human body, forming the bulk of the buttock.',
    fn: 'Extends the hip — the primary driver in standing up, climbing, sprinting, and jumping.',
    bodyweight: ['Glute bridges', 'Single-leg hip thrusts', 'Step-ups'],
    weights: ['Barbell hip thrusts', 'Squats', 'Romanian deadlifts'],
    sport: "Powers the sprawl, the shot and the hip escape. Weak glutes push the load into the lower back and hamstrings, which is where the injuries then show up.",
  },
  quads: {
    name: 'Quadriceps',
    latin: 'Quadriceps femoris',
    region: 'Front thigh',
    desc: 'The four-headed muscle group on the front of the thigh, converging into the patellar tendon.',
    fn: 'Extends the knee; the rectus femoris head also flexes the hip.',
    bodyweight: ['Pistol squats', 'Bulgarian split squats', 'Wall sits', 'Sissy squats'],
    weights: ['Squats', 'Leg press', 'Leg extensions'],
    sport: "The dead leg — a deep quad contusion from a knee or a low kick — is one of the commonest fight injuries. Repeated bleeding into the muscle risks myositis ossificans, where bone forms inside the bruise.",
  },
  hams: {
    name: 'Hamstrings',
    latin: 'Biceps femoris, semitendinosus, semimembranosus',
    region: 'Back thigh',
    desc: 'Three long muscles down the back of the thigh, crossing both hip and knee.',
    fn: 'Flex the knee and extend the hip; decelerate the leg when sprinting.',
    bodyweight: ['Nordic curls', 'Sliding leg curls', 'Single-leg bridges'],
    weights: ['Romanian deadlifts', 'Leg curls', 'Good mornings'],
    sport: "Strained during the shot and the sprawl, where the muscle lengthens under load. Hamstring tears are the classic recurrence injury: the reinjury rate in the first weeks back is high.",
  },
  calves: {
    name: 'Calves',
    latin: 'Gastrocnemius & soleus',
    region: 'Lower leg',
    desc: 'The twin-bellied gastrocnemius over the deeper soleus, tapering into the Achilles tendon.',
    fn: 'Plantar-flex the ankle — pointing the foot to walk, run, and jump.',
    bodyweight: ['Single-leg calf raises', 'Jump rope', 'Pogo hops'],
    weights: ['Standing calf raises', 'Seated calf raises'],
    sport: "Checked low kicks slam into the calf, and explosive level changes strain it. A sudden pop mid-round is often 'tennis leg' — a tear where the calf meets the Achilles.",
  },
};

// Display order for the sidebar list.
export const MUSCLE_ORDER = [
  'traps', 'delts', 'pecs', 'biceps', 'triceps', 'forearms',
  'abs', 'obliques', 'lats', 'lowback',
  'glutes', 'quads', 'hams', 'calves',
];
