// Selectable parts for the non-muscle system tabs.
// Ids match the GLB node names (sk_ / nv_ / td_ / fs_ prefixes).
// `note` is an optional third section — the thing worth knowing.

export const SKELETON = {
  sk_skull: {
    name: 'Skull & teeth',
    latin: 'Cranium',
    region: 'Head',
    desc: 'Twenty-two bones — most locked together at jagged sutures — plus the jaw and thirty-two teeth. The mandible is the only skull bone that moves freely.',
    fn: 'Encases the brain, frames the face and airways, and anchors the chewing muscles.',
    note: 'The sutures stay slightly mobile for life; in infants they are still open as fontanelles, letting the head deform during birth and the brain triple in volume.',
    sport: "The central risk in striking sports. A knockout is rotational acceleration of the brain inside the skull, and the cumulative load — including the subconcussive shots taken in sparring — is what links boxing and MMA to chronic traumatic encephalopathy. Orbital floor blowouts, nasal fractures and mandible fractures are the common bony injuries.",
  },
  sk_spine: {
    name: 'Spine',
    latin: 'Columna vertebralis',
    region: 'Axial skeleton',
    desc: 'Thirty-three vertebrae — 7 cervical, 12 thoracic, 5 lumbar, then the fused sacrum and coccyx — stacked on twenty-three shock-absorbing discs.',
    fn: 'Carries the trunk, protects the spinal cord, and lets you bend and twist.',
    note: 'Its double S-curve is what makes upright walking cheap: the curves act as a leaf spring, cutting the jolt that reaches your skull with every heel strike.',
    sport: "The neck absorbs slams, spikes and cranks. Wrestlers bridge on it deliberately; a suplex landing on the head is the mechanism behind catastrophic cervical injury. Chronic disc disease in the neck is common in career grapplers.",
  },
  sk_ribs: {
    name: 'Rib cage',
    latin: 'Cavea thoracis',
    region: 'Thorax',
    desc: 'Twelve pairs of ribs meeting the sternum through springy costal cartilage. The lowest two pairs float, anchored only at the spine.',
    fn: 'Shields the heart and lungs, and moves with every breath.',
    note: 'Breathing in swings the ribs up and out like a bucket handle, widening the chest in two directions at once.',
    sport: "Body shots, knees and being stacked crack ribs and, more often, separate the costal cartilage. Cartilage injuries barely show on X-ray, hurt with every breath, and can take three months to settle — a fight-camp killer.",
  },
  sk_shoulder: {
    name: 'Shoulder girdle',
    latin: 'Cingulum pectorale',
    region: 'Shoulder',
    desc: 'Clavicle and scapula. The collarbone is the only bony strut tying the arm to the trunk; the shoulder blade simply floats on muscle over the rib cage.',
    fn: 'Suspends the arm and gives the shoulder its enormous range.',
    note: 'That floating arrangement buys mobility at the cost of stability — which is why the shoulder is the most frequently dislocated joint in the body.',
    sport: "Landing on the point of the shoulder separates the AC joint; landing on an outstretched arm breaks the clavicle. Both are standard judo and wrestling injuries from being thrown.",
  },
  sk_arm: {
    name: 'Humerus',
    latin: 'Humerus',
    region: 'Upper arm',
    desc: 'The long bone of the upper arm: a ball joint with the scapula above, a hinge with the forearm below.',
    fn: 'The lever behind every press, pull, and throw.',
    note: 'The radial nerve spirals directly against its shaft, so a mid-shaft fracture classically causes wrist drop.',
    sport: "Rarely broken, but a fully applied armbar or kimura on a resisting athlete can spiral-fracture the shaft. The radial nerve wraps the bone, so such a break can leave a temporary wrist drop.",
  },
  sk_forearm: {
    name: 'Radius & ulna',
    latin: 'Radius et ulna',
    region: 'Forearm',
    desc: 'Paired bones joined along their length by an interosseous membrane. The radius crosses over the ulna when the palm turns down.',
    fn: 'Hinge at the elbow and rotate the hand through pronation and supination.',
    note: 'A fall on an outstretched hand most often breaks the radius just above the wrist — the Colles fracture, among the commonest breaks in people over fifty.',
    sport: "The blocking bone. Checking hard kicks and covering up bruises the ulna, and a direct blow on a raised guard can crack it — the nightstick fracture.",
  },
  sk_hand: {
    name: 'Hand bones',
    latin: 'Ossa manus',
    region: 'Hand',
    desc: 'Twenty-seven bones per hand: eight carpals in two rows, five metacarpals, and fourteen phalanges.',
    fn: 'A chain of small joints trading raw power for precision.',
    note: 'A quarter of all the bones in your body are in your two hands — the anatomical price of a truly opposable thumb.',
    sport: "The boxer's fracture — a broken neck of the fifth metacarpal — comes from punching with a poorly aligned fist. Hand injuries are the most frequent injury in professional boxing, which is what hand wraps and glove padding exist to reduce.",
  },
  sk_pelvis: {
    name: 'Pelvis',
    latin: 'Cingulum pelvicum',
    region: 'Hip',
    desc: 'Two hip bones — each a fusion of ilium, ischium, and pubis — closing the ring with the sacrum behind.',
    fn: 'Funnels the trunk’s weight into the legs and anchors the hip muscles.',
    note: 'The three bones fuse only in the mid-teens; before that they remain joined by a Y-shaped cartilage inside the hip socket.',
    sport: "Takes hip-pointer contusions from mat and cage impacts. In teenage athletes, an explosive sprint or kick can avulse the bony attachment where a hip flexor or hamstring pulls.",
  },
  sk_femur: {
    name: 'Femur & patella',
    latin: 'Femur, patella',
    region: 'Thigh',
    desc: 'The longest and strongest bone in the body, angled inward from hip to knee, plus the kneecap riding inside the quadriceps tendon.',
    fn: 'Carries you through every stride; the patella boosts the quadriceps’ leverage.',
    note: 'The patella is a sesamoid — a bone grown inside a tendon — and it increases the quadriceps’ pull on the shin by up to half.',
    sport: "Almost never broken in sport — it takes a car-crash level of force. The vulnerable parts are the kneecap, which can dislocate laterally during a twisting scramble, and the femoral head's cartilage.",
  },
  sk_leg: {
    name: 'Tibia & fibula',
    latin: 'Tibia et fibula',
    region: 'Lower leg',
    desc: 'The weight-bearing shin bone and the slender fibula beside it, splinted together by an interosseous membrane.',
    fn: 'The tibia carries the load; the fibula anchors muscle and braces the ankle.',
    note: 'The fibula bears almost no body weight, which is why surgeons harvest lengths of it to rebuild jaws and other bones elsewhere.',
    sport: "The most infamous fracture in MMA: a low kick met by a raised shin can snap the kicker's tibia and fibula. Shin conditioning thickens the bone over years, but the mechanics of a mistimed check are unforgiving.",
  },
  sk_foot: {
    name: 'Foot bones',
    latin: 'Ossa pedis',
    region: 'Foot',
    desc: 'Twenty-six bones per foot — seven tarsals, five metatarsals, fourteen phalanges — arranged into three arches.',
    fn: 'Absorbs landing forces and turns each step into an elastic push-off.',
    note: 'The arches store and return roughly a sixth of the energy of every running stride, working like a spring under the foot.',
    sport: "Kicking with the instep instead of the shin breaks metatarsals. Toes get jammed and dislocated on mats and in the cage — 'mat toe' is a chronic nuisance for grapplers.",
  },
};

export const SKELETON_ORDER = [
  'sk_skull', 'sk_spine', 'sk_ribs', 'sk_shoulder', 'sk_arm', 'sk_forearm',
  'sk_hand', 'sk_pelvis', 'sk_femur', 'sk_leg', 'sk_foot',
];

export const NERVES = {
  nv_cerebrum: {
    name: 'Cerebrum',
    latin: 'Cerebrum',
    region: 'Central nervous system',
    desc: 'The folded outer brain — two hemispheres of cortex divided into frontal, parietal, temporal, and occipital lobes, wrapped in three membranes.',
    fn: 'Handles thought, language, planning, voluntary movement, and conscious sensation.',
    note: 'Its folding packs about 2,000 cm² of cortex into the skull; roughly two thirds of that surface is hidden down inside the grooves.',
    sport: "Repeated blows to the head damage the cortex over a career, not just in the knockouts. CTE — first described in boxers as dementia pugilistica — is associated with the cumulative number of blows absorbed rather than the number of diagnosed concussions, which is why sparring volume is now managed as carefully as fights.",
  },
  nv_deepbrain: {
    name: 'Deep brain structures',
    latin: 'Diencephalon & nuclei basales',
    region: 'Central nervous system',
    desc: 'Thalamus, hypothalamus, basal ganglia, hippocampus, corpus callosum, and the fluid-filled ventricles beneath the cortex.',
    fn: 'Relay and gate all incoming sensation, tune movement, drive appetite and body clock, and lay down memory.',
    note: 'Almost every sense routes through the thalamus before reaching the cortex — smell is the one exception, going straight to the forebrain.',
    sport: "Rotational impacts shear long white-matter tracts, and the corpus callosum is among the first structures to show change on imaging in career fighters. Damage here produces the slowed processing and memory problems seen before any outward symptoms appear.",
  },
  nv_cerebellum: {
    name: 'Cerebellum',
    latin: 'Cerebellum',
    region: 'Central nervous system',
    desc: 'The tightly pleated "little brain" tucked beneath the back of the cerebrum.',
    fn: 'Times and smooths movement, maintains balance, and stores motor skills.',
    note: 'It is about a tenth of the brain by volume yet holds over half its neurons — the densest wiring in the nervous system.',
    sport: "The slurred speech, tremor and unsteady walk of the classic 'punch-drunk' syndrome are cerebellar. Balance loss immediately after a hard shot is this system briefly failing.",
  },
  nv_brainstem: {
    name: 'Brainstem',
    latin: 'Truncus encephali',
    region: 'Central nervous system',
    desc: 'Midbrain, pons, and medulla oblongata — the stalk connecting brain to spinal cord, and the origin of most cranial nerves.',
    fn: 'Runs breathing, heart rate, blood pressure, swallowing, and consciousness itself.',
    note: 'The motor tracts cross sides here, in the pyramids of the medulla — which is why one hemisphere controls the opposite half of the body.',
    sport: "A knockout is a transient disruption of the brainstem's arousal system — which is why consciousness switches off instantly and returns within seconds. The stiff-arm 'fencing response' seen after some knockouts is a brainstem reflex, and a reliable sign that the impact was significant.",
  },
  nv_cord: {
    name: 'Spinal cord',
    latin: 'Medulla spinalis',
    region: 'Central nervous system',
    desc: 'A cable about as thick as a finger running down the vertebral canal, giving off 31 pairs of spinal nerves and ending near the first lumbar vertebra in the cauda equina.',
    fn: 'Carries traffic between brain and body, and runs reflexes without consulting the brain.',
    note: 'Because the cord stops well above the end of the spine, a lumbar puncture below that level meets only floating nerve roots, which drift aside from the needle.',
    sport: "Spearing head-first or being spiked on the head can cause cervical cord neurapraxia — a temporary burning paralysis of all four limbs that resolves in minutes to hours, but demands imaging and a hard look at technique before returning.",
  },
  nv_optic: {
    name: 'Visual pathway',
    latin: 'Nervus opticus',
    region: 'Head',
    desc: 'The optic nerves, their crossing at the chiasm, and the tracts running back toward the brain.',
    fn: 'Carries sight from the retina to the visual cortex.',
    note: 'At the chiasm only the inner half of each nerve crosses, so each side of the brain receives the opposite half of the visual world rather than one whole eye.',
    sport: "Boxers carry a well-documented risk of retinal detachment and traumatic cataract from repeated blows to the eye, which is why licensing bodies require regular eye examinations. Eye pokes in MMA cause corneal abrasions and can end fights outright.",
  },
  nv_trigeminal: {
    name: 'Trigeminal nerve',
    latin: 'Nervus trigeminus (V)',
    region: 'Face & jaw',
    desc: 'The largest cranial nerve, splitting into ophthalmic, maxillary, and mandibular divisions across the face.',
    fn: 'Supplies all facial sensation and drives the chewing muscles.',
    note: 'It is the nerve a dentist blocks before working on the lower teeth — and the one that misfires in trigeminal neuralgia, causing stabbing facial pain.',
    sport: "An orbital floor fracture typically leaves numbness of the cheek and upper lip, because the infraorbital branch runs through the fractured floor. That numbness is often what reveals the fracture.",
  },
  nv_cranial: {
    name: 'Other cranial nerves',
    latin: 'Nervi craniales',
    region: 'Head & neck',
    desc: 'The remaining eleven pairs leaving the brain directly — smell, eye movement, facial expression, hearing and balance, taste, swallowing, and the wandering vagus.',
    fn: 'Wire the head and face, and through the vagus reach the heart, lungs, and gut.',
    note: 'The vagus is the outlier: it wanders far past the head, and most of its fibres report upward from the organs rather than sending commands down.',
    sport: "A liver shot works partly through visceral afferents in the vagus, dropping heart rate and blood pressure and folding a fighter with no head trauma at all. Repeated ear trauma damages the structures behind the vestibular nerve, causing lasting dizziness.",
  },
  nv_sympathetic: {
    name: 'Autonomic chain',
    latin: 'Truncus sympathicus',
    region: 'Alongside the spine',
    desc: 'The paired sympathetic trunks — beaded chains of ganglia running the length of the spine — and the visceral nerves branching from them.',
    fn: 'Runs fight-or-flight: heart rate, blood vessel tone, sweating, pupil size, digestion.',
    note: 'None of it is under voluntary control, yet it adjusts continuously — this is the machinery behind a racing heart before you consciously register a fright.',
    sport: "Blood chokes work on the carotid vessels and their baroreceptors, not the airway, and can produce unconsciousness in around ten seconds. The adrenaline surge that masks pain during a round is this system too, which is why injuries are often first felt in the locker room.",
  },
  nv_brachial: {
    name: 'Brachial plexus',
    latin: 'Plexus brachialis',
    region: 'Neck & shoulder',
    desc: 'Nerve roots C5–T1 braiding through trunks, divisions, and cords behind the collarbone before splitting into the arm’s main nerves.',
    fn: 'The single gateway for every nerve signal to and from the arm.',
    note: 'A hard shoulder-and-neck impact can wrench the upper roots — the "stinger" that leaves a burning arm for minutes after a tackle.',
    sport: "The stinger or burner — the signature nerve injury of wrestling and football. A shoulder driven down while the neck bends away stretches the upper roots, giving a burning shock down one arm with brief weakness. Repeated stingers deserve investigation, not a shrug.",
  },
  nv_median: {
    name: 'Median nerve',
    latin: 'Nervus medianus',
    region: 'Arm & hand',
    desc: 'Runs down the middle of the arm and passes through the carpal tunnel at the wrist alongside nine tendons.',
    fn: 'Drives most forearm flexors and thumb muscles; senses the palm side of the thumb, index, and middle fingers.',
    note: 'Squeezed in the carpal tunnel it produces the classic night-time tingling of the first three fingers — the commonest nerve entrapment there is.',
    sport: "Wrist locks and long gripping bouts compress the median nerve at the wrist, giving the night-time tingling of the thumb, index and middle fingers.",
  },
  nv_ulnar: {
    name: 'Ulnar nerve',
    latin: 'Nervus ulnaris',
    region: 'Arm & hand',
    desc: 'Passes behind the inner knob of the elbow, exposed just under the skin, then runs to the little-finger side of the hand.',
    fn: 'Powers most of the small hand muscles that grip and spread the fingers.',
    note: 'That exposed stretch at the elbow is the "funny bone" — hitting it fires straight into the ring and little fingers.',
    sport: "Grapplers irritate the ulnar nerve at the elbow constantly — it sits exposed on the mat side of every elbow post, and kimura and armbar positions stretch it. Chronic numbness of the ring and little fingers is common in long-time BJJ players.",
  },
  nv_radial: {
    name: 'Radial & axillary nerves',
    latin: 'Nervus radialis, nervus axillaris',
    region: 'Shoulder & arm',
    desc: 'The radial nerve spirals around the back of the humerus into the forearm; the axillary nerve wraps the shoulder to reach the deltoid.',
    fn: 'Straighten the elbow, wrist, and fingers; the axillary lifts the arm out sideways.',
    note: 'Falling asleep with an arm over a chair back can compress the radial nerve — "Saturday night palsy", a temporarily limp wrist.',
    sport: "A humeral shaft fracture from an over-applied armbar, or prolonged compression under an opponent's weight, can leave a wrist drop that takes weeks to months to recover.",
  },
  nv_intercostal: {
    name: 'Chest wall nerves',
    latin: 'Nervi intercostales',
    region: 'Thorax',
    desc: 'Intercostal nerves running in the sheltered groove under each rib, plus the phrenic nerve descending from the neck to the diaphragm.',
    fn: 'Power the breathing muscles and carry sensation from the chest wall.',
    note: 'The phrenic starts in the neck (C3–C5) and travels all the way to the diaphragm, so a high neck injury can stop breathing outright.',
    sport: "The pain after a rib injury is largely intercostal nerve pain: sharp with each breath, each rotation and each punch thrown, which is why rib injuries derail camps out of proportion to the imaging.",
  },
  nv_lumbar: {
    name: 'Lumbar plexus',
    latin: 'Plexus lumbalis',
    region: 'Lower back & thigh',
    desc: 'Roots L1–L4 weaving inside the psoas muscle into the femoral, obturator, and saphenous nerves.',
    fn: 'Drive the front and inner thigh; the femoral nerve is what straightens your knee.',
    note: 'The saphenous branch runs to the inner ankle — the reason a knee problem can be felt low down the inside of the shin.',
    sport: "A lumbar disc pressing on a root gives leg pain, not just back pain. In heavy lifters and wrestlers this is the usual reason a 'back injury' refuses to settle.",
  },
  nv_sciatic: {
    name: 'Sciatic nerve',
    latin: 'Nervus ischiadicus',
    region: 'Buttock & thigh',
    desc: 'The largest nerve in the body — about as thick as a thumb where it leaves the pelvis and runs beneath the glutes down the back of the thigh.',
    fn: 'Supplies the hamstrings and, through its branches, everything below the knee.',
    note: 'Irritated at its roots — usually by a lumbar disc — it refers pain down the whole limb: sciatica.',
    sport: "Sciatica from a lumbar disc is the standard chronic complaint of grapplers with heavy training histories; deep piriformis tightness after long guard-playing sessions can mimic it.",
  },
  nv_tibial: {
    name: 'Tibial nerve',
    latin: 'Nervus tibialis',
    region: 'Calf & sole',
    desc: 'The larger branch of the sciatic, running down the back of the calf and behind the inner ankle into the sole.',
    fn: 'Powers the calf and the small muscles of the sole; senses the underside of the foot.',
    note: 'It passes through its own tight tunnel behind the inner ankle, where compression causes burning pain in the sole.',
    sport: "Compressed behind the inner ankle after repeated heel impacts and ankle sprains, producing burning in the sole that barefoot mat training aggravates.",
  },
  nv_fibular: {
    name: 'Fibular nerves',
    latin: 'Nervus fibularis',
    region: 'Shin & foot',
    desc: 'The sciatic’s outer branch, winding around the neck of the fibula just under the skin before dividing across the shin and foot.',
    fn: 'Lift the foot and toes, and turn the sole outward.',
    note: 'Its exposed wrap around the fibula makes it the most commonly injured nerve in the leg — crossed legs or a tight cast can cause foot drop.',
    sport: "The most exposed nerve in the leg, wrapping the fibula just under the skin at the outer knee. Heel hooks and knee dislocations can damage it, and a low kick landing there causes an instant dead-leg; injury shows as foot drop.",
  },
  nv_sacral: {
    name: 'Sacral plexus & pelvic nerves',
    latin: 'Plexus sacralis',
    region: 'Pelvis & buttock',
    desc: 'Roots L4–S4 on the back wall of the pelvis, giving the gluteal nerves and the pudendal nerve.',
    fn: 'Power the buttock muscles that hold you level on one leg, and the pelvic floor.',
    note: 'Damage to the superior gluteal nerve shows up as a telltale hip drop on the opposite side with each step.',
    sport: "Takes deep contusions in the buttock from mat and cage impacts. Weakness of the gluteal nerves shows up as a hip that drops on every step — a subtle but real drag on takedown power.",
  },
};

export const NERVES_ORDER = [
  'nv_cerebrum', 'nv_deepbrain', 'nv_cerebellum', 'nv_brainstem', 'nv_cord',
  'nv_optic', 'nv_trigeminal', 'nv_cranial', 'nv_sympathetic',
  'nv_brachial', 'nv_median', 'nv_ulnar', 'nv_radial', 'nv_intercostal',
  'nv_lumbar', 'nv_sciatic', 'nv_tibial', 'nv_fibular', 'nv_sacral',
];

export const TENDONS = {
  td_achilles: {
    name: 'Achilles tendon',
    latin: 'Tendo calcaneus',
    region: 'Ankle',
    desc: 'The thickest and strongest tendon in the body, joining both calf muscles to the heel bone.',
    fn: 'Transmits the calf’s force to the heel — the spring behind every step, hop, and sprint.',
    note: 'It routinely carries loads of six to twelve times body weight when running, and its fibres spiral about 90° on the way down, which concentrates stress a few centimetres above the heel where ruptures occur.',
    sport: "Ruptures on an explosive push-off, often with an audible pop and the sensation of being kicked in the heel. Heel hooks also load it hard. Repair plus rehabilitation typically takes the better part of a year before full return to competition.",
  },
  td_patellar: {
    name: 'Patellar tendon',
    latin: 'Ligamentum patellae',
    region: 'Knee',
    desc: 'The continuation of the quadriceps tendon below the kneecap, anchoring into the shin, with the patellar retinacula fanning out either side.',
    fn: 'Delivers the quadriceps’ pull across the knee to straighten the leg.',
    note: 'Tap it and the leg kicks — the knee-jerk reflex, a signal that never reaches the brain before the muscle responds.',
    sport: "Jumper's knee — patellar tendinopathy — comes from the constant level changes, sprawls and plyometric work in fight training, and it grumbles for months rather than tearing outright.",
  },
  td_cruciate: {
    name: 'Cruciate ligaments',
    latin: 'Ligamenta cruciata genus',
    region: 'Inside the knee',
    desc: 'The anterior and posterior cruciates, crossing like an X in the middle of the knee joint.',
    fn: 'Stop the shin sliding forward or backward under the thigh bone, and control rotation.',
    note: 'The ACL usually tears without contact at all — a sudden decelerate-and-pivot — and because it heals poorly it is among the most reconstructed structures in sport.',
    sport: "The ACL tears in twisting scrambles, hard takedowns and knee bars, usually without contact. It is among the most season-ending injuries in combat sport: reconstruction plus rehabilitation runs nine to twelve months, and the reinjury risk on return is real.",
  },
  td_kneecoll: {
    name: 'Knee collaterals & menisci',
    latin: 'Ligamenta collateralia, menisci',
    region: 'Knee',
    desc: 'The medial and lateral collateral ligaments guarding each side, plus the two C-shaped menisci cushioning the joint surfaces.',
    fn: 'Resist sideways forces and spread load across the knee.',
    note: 'The medial collateral is fused to the medial meniscus, so one blow to the outside of the knee often injures both at once.',
    sport: "The MCL takes the sprawl and the knee-on-mat landing; the menisci tear when a planted foot twists during a shot. Meniscus damage is what turns into the chronic swollen knee of veteran wrestlers.",
  },
  td_ankleliga: {
    name: 'Ankle ligaments',
    latin: 'Ligamenta articulationis talocruralis',
    region: 'Ankle',
    desc: 'The three-part lateral complex on the outside and the broad deltoid ligament on the inside.',
    fn: 'Hold the talus in its socket while allowing the ankle to hinge.',
    note: 'Rolling the ankle inward strains the anterior talofibular ligament first — the single most common sprain in the body.',
    sport: "The most common sprain in sport, and in grappling the lateral ligaments are also the tissue a heel hook attacks. Heel hooks are dangerous precisely because the knee and ankle ligaments fail before pain forces the tap.",
  },
  td_hipliga: {
    name: 'Hip ligaments',
    latin: 'Ligamenta articulationis coxae',
    region: 'Hip & pelvis',
    desc: 'The iliofemoral, pubofemoral, and ischiofemoral ligaments spiralling around the hip socket, plus the sacrotuberous and sacrospinous behind.',
    fn: 'Screw tight as you stand upright, locking the hip with barely any muscular effort.',
    note: 'The iliofemoral is the strongest ligament in the body, capable of holding around 350 kg — it is what lets you stand all day without tiring your hips.',
    sport: "Deep guard positions and repeated end-range hip loading are associated with labral tears and femoroacetabular impingement in grapplers, giving a pinching groin pain that limits the shot.",
  },
  td_shoulderliga: {
    name: 'Shoulder ligaments',
    latin: 'Ligamenta articulationis humeri',
    region: 'Shoulder',
    desc: 'The glenohumeral ligaments reinforcing the joint capsule, with the acromioclavicular and coracoclavicular ligaments strapping the collarbone down.',
    fn: 'Provide what little passive restraint the shoulder has.',
    note: 'A fall onto the point of the shoulder tears the acromioclavicular ligaments — the "separated shoulder", distinct from a dislocation.',
    sport: "The kimura and americana load the shoulder's capsule and ligaments directly; a throw landing on the shoulder separates the AC joint. Labral tears from repeated arm-in positions are the reason many veterans cannot sleep on one side.",
  },
  td_spineliga: {
    name: 'Spinal ligaments',
    latin: 'Ligamenta columnae vertebralis',
    region: 'Spine',
    desc: 'The long anterior and posterior longitudinal ligaments running the length of the spine, the elastic ligamenta flava between the arches, and the interspinous and supraspinous ligaments behind.',
    fn: 'Bind the vertebrae together and limit how far the spine can bend.',
    note: 'The ligamenta flava are unusually rich in elastin — they stay under tension even at rest, helping to pull you back upright after a bend.',
    sport: "Neck cranks and whiplash from slams sprain the spinal ligaments. Ligament injury heals slowly and leaves segments subtly loose, which is part of why chronic neck pain persists after the acute injury settles.",
  },
  td_elbowliga: {
    name: 'Elbow ligaments',
    latin: 'Ligamenta articulationis cubiti',
    region: 'Elbow',
    desc: 'The collateral ligaments on each side and the annular ligament that loops around the head of the radius.',
    fn: 'Keep the hinge stable and hold the radius in place as it spins.',
    note: 'The annular loop is loose in small children, so a sharp pull on the arm can slip the radius out of it — "nursemaid’s elbow".',
    sport: "The armbar's target. Hyperextension tears the collateral ligaments and joint capsule, and a fighter who refuses to tap can leave the cage with a joint that is unstable for months. Repeated submissions to armbars cause cumulative laxity.",
  },
  td_inguinal: {
    name: 'Inguinal ligament',
    latin: 'Ligamentum inguinale',
    region: 'Groin',
    desc: 'The rolled-under lower border of the external oblique aponeurosis, running from the hip bone to the pubis.',
    fn: 'Forms the floor of the inguinal canal and the boundary between abdomen and thigh.',
    note: 'It is the landmark that separates the two kinds of groin hernia — above it, inguinal; below it, femoral.',
    sport: "Athletic pubalgia — the 'sports hernia' — is a tear of the tissue around this region from repeated explosive twisting and shooting. It is notoriously slow to diagnose and a common cause of vague, persistent groin pain in wrestlers.",
  },
  td_foottendon: {
    name: 'Foot tendons',
    latin: 'Tendines pedis',
    region: 'Foot & ankle',
    desc: 'The tibialis, fibularis, and long toe tendons crossing the ankle to reach the foot.',
    fn: 'Lift, lower, and steer the foot, and support its arches.',
    note: 'Tibialis posterior slings under the arch like a stirrup; when it fails, the arch gradually collapses into a flat foot.',
    sport: "Tibialis posterior and the long toe tendons take repeated strain from barefoot mat work and kicking. Kicking with the instep is what tears them.",
  },
};

export const TENDONS_ORDER = [
  'td_achilles', 'td_patellar', 'td_cruciate', 'td_kneecoll', 'td_ankleliga',
  'td_hipliga', 'td_shoulderliga', 'td_spineliga', 'td_elbowliga',
  'td_inguinal',
  'td_foottendon',
];

export const FASCIA = {
  fs_thoraco: {
    name: 'Thoracolumbar fascia',
    latin: 'Fascia thoracolumbalis',
    region: 'Lower back',
    desc: 'A diamond of layered sheets over the lower back, where the lats, glutes, and deep spinal muscles all take hold.',
    fn: 'Transfers force diagonally between one lat and the opposite glute — the body’s cross-brace.',
    note: 'That diagonal link is why a heavy carry in one hand is felt across the opposite lower back; it is densely supplied with nerve endings and a suspected source of non-specific back pain.',
    sport: "The sheet that transfers force between one lat and the opposite glute — exactly the diagonal loading of a throw or a sprawl. Densely innervated, it is a suspected source of the non-specific low back pain so common in wrestlers.",
  },
  fs_lata: {
    name: 'Fascia lata',
    latin: 'Fascia lata',
    region: 'Thigh',
    desc: 'The tough stocking wrapping the whole thigh and dividing it into compartments.',
    fn: 'Compresses the thigh muscles, improving their pump and force transfer.',
    note: 'Because it is inelastic, swelling inside a compartment has nowhere to go — the basis of compartment syndrome after a crush injury.',
    sport: "Because this sleeve does not stretch, bleeding into the thigh after a deep contusion has nowhere to go. A hard dead leg that keeps worsening with rising pressure and tightness is a surgical emergency, not a bruise.",
  },
  fs_itband: {
    name: 'Iliotibial band',
    latin: 'Tractus iliotibialis',
    region: 'Outer thigh',
    desc: 'The thickened outer stripe of the fascia lata, running from the hip crest to just below the knee.',
    fn: 'Stabilises the knee and hip in stance and stores elastic energy when running.',
    note: 'It is far too stiff to "stretch out" — around 1,500 N to lengthen it a single percent — so friction pain at the knee is treated by fixing hip control, not by stretching the band.',
    sport: "Low kicks land directly on it, and its friction against the outer knee causes a chronic ache in fighters doing high running volume. It is far too stiff to stretch out, so management is hip strength, not foam rolling.",
  },
  fs_plantar: {
    name: 'Plantar fascia',
    latin: 'Aponeurosis plantaris',
    region: 'Sole of foot',
    desc: 'A fan of dense fascia from the heel bone forward into the toes.',
    fn: 'Supports the arch and tightens as the toes bend back, turning the foot into a rigid lever.',
    note: 'That windlass tightening is why plantar fasciitis hurts most on the first steps out of bed, when the tissue has shortened overnight.',
    sport: "Barefoot mat and ring training loads the sole constantly. Plantar fasciitis hurts most on the first steps out of bed, and once established it commonly runs for months.",
  },
  fs_palmar: {
    name: 'Palmar fascia',
    latin: 'Aponeurosis palmaris',
    region: 'Palm',
    desc: 'The tough triangular sheet just under the skin of the palm, with the thinner dorsal fascia on the back of the hand.',
    fn: 'Anchors the palm’s skin so a grip does not slide.',
    note: 'It can thicken into cords that pull the fingers into the palm — Dupuytren’s contracture, which most often takes the ring and little fingers.',
    sport: "Gripping gis and hand wraps loads the palm's fascia; over years it can thicken into cords that pull the ring and little fingers toward the palm.",
  },
  fs_galea: {
    name: 'Galea aponeurotica',
    latin: 'Galea aponeurotica',
    region: 'Scalp',
    desc: 'The tendon sheet capping the skull, linking the forehead and back-of-head muscles into one sheet.',
    fn: 'Lets the scalp glide over the skull and raises the eyebrows.',
    note: 'It binds skin, fat, and muscle into a single layer, which is why scalp wounds gape open and bleed so freely.',
    sport: "The layer behind the cut. Elbows and headbutts split the scalp and brow down to this sheet, and because it binds skin and muscle together the wounds gape and bleed hard — which is why cuts stop fights far more often than the underlying damage warrants.",
  },
  fs_abdominal: {
    name: 'Abdominal aponeuroses',
    latin: 'Vagina musculi recti abdominis',
    region: 'Abdomen',
    desc: 'The flat tendon sheets of the abdominal wall — the rectus sheath enclosing the six-pack and the linea alba running down the midline.',
    fn: 'Wrap and brace the abdominal wall into one continuous corset.',
    note: 'The linea alba can stretch and separate in late pregnancy or with heavy lifting — diastasis recti, a gap rather than a tear.',
    sport: "The tissue that fails in athletic pubalgia. Repeated explosive rotation and shooting strain the abdominal wall where it meets the groin, producing pain that is neither a true hernia nor a simple strain.",
  },
  fs_retinacula: {
    name: 'Retinacula',
    latin: 'Retinacula',
    region: 'Wrist & ankle',
    desc: 'Straps of thickened fascia bridging the front and back of the wrist and ankle.',
    fn: 'Hold the long tendons close to the joint so they cannot bowstring away when it bends.',
    note: 'The flexor retinaculum at the wrist forms the roof of the carpal tunnel — cutting it is the standard release operation.',
    sport: "The straps that stop tendons bowstringing at the wrist and ankle. Taping and wraps essentially reinforce their job, which is why grapplers with chronic wrist pain tape before every session.",
  },
  fs_septa: {
    name: 'Intermuscular septa',
    latin: 'Septa intermuscularia',
    region: 'Arms & legs',
    desc: 'Sheets diving inward from the deep fascia to the bone, walling the limbs into compartments.',
    fn: 'Separate muscle groups and give them extra surface to attach to.',
    note: 'They define the compartments surgeons open in an emergency fasciotomy when pressure inside a limb rises dangerously.',
    sport: "These walls create closed compartments, and that is the danger after a hard shin or forearm trauma: swelling inside a compartment raises pressure until circulation fails. Acute compartment syndrome needs surgical release within hours.",
  },
  fs_crural: {
    name: 'Crural fascia',
    latin: 'Fascia cruris',
    region: 'Lower leg',
    desc: 'The deep fascia sleeve of the lower leg, continuous with the popliteal fascia behind the knee.',
    fn: 'Binds the calf muscles into compartments and assists the calf’s venous pump.',
    note: 'Each calf contraction squeezes the veins inside this sleeve and pushes blood uphill — the reason standing still makes the legs swell.',
    sport: "Checked kicks and shin-on-shin trauma bleed into this tight sleeve. Most settle as bruises; the rare one that keeps building pressure is a compartment syndrome and an emergency.",
  },
  fs_armfascia: {
    name: 'Brachial fascia',
    latin: 'Fascia brachii et antebrachii',
    region: 'Arm & forearm',
    desc: 'The deep fascia sleeve of the upper arm and forearm.',
    fn: 'Compartmentalises the arm’s flexors and extensors and transmits their force.',
    note: 'The bicipital aponeurosis fans off the biceps across this fascia, shielding the artery beneath — which is why blood is drawn safely just there at the elbow.',
    sport: "The reason forearms 'pump' and grips fail late in a round — the sleeve limits how much the working muscle can swell.",
  },
  fs_pectoral: {
    name: 'Pectoral fascia',
    latin: 'Fascia pectoralis',
    region: 'Chest',
    desc: 'The fascia over the pectoralis major, continuous with the deeper clavipectoral fascia and the deltoid fascia at the shoulder.',
    fn: 'Wraps the chest muscles and blends into the fascia of the arm and abdomen.',
    note: 'It runs continuously into the abdominal fascia below and the arm fascia beside — one of the clearest examples of fascia as a single body-wide web.',
    sport: "Overlies the pec major, so it is the layer under the deep bruising and the visible hollow when that muscle tears off its insertion.",
  },
  fs_cervical: {
    name: 'Cervical fascia',
    latin: 'Fascia cervicalis',
    region: 'Neck',
    desc: 'Concentric fascial sleeves wrapping the neck’s muscles, airway, and vessels.',
    fn: 'Organise the neck into compartments and let its structures slide as you swallow and turn.',
    note: 'The spaces between these layers run straight down into the chest, which is how a deep neck infection can descend into the mediastinum.',
    sport: "Wraps the neck's muscles and vessels. Its layered spaces let deep infections track down into the chest, which is why a neglected infected mat burn on the neck is treated seriously.",
  },
  fs_sheaths: {
    name: 'Tendon sheaths',
    latin: 'Vaginae tendinum',
    region: 'Wrist, hand & ankle',
    desc: 'Fluid-filled tubes wrapping the long tendons where they cross joints.',
    fn: 'Lubricate the tendons so they glide with almost no friction.',
    note: 'Inflame one at the thumb side of the wrist and the thumb hurts to move — de Quervain’s tenosynovitis.',
    sport: "Long gripping sessions inflame the sheaths at the wrist and thumb, giving the tenosynovitis that makes gripping and even opening a door painful.",
  },
};

export const FASCIA_ORDER = [
  'fs_thoraco', 'fs_lata', 'fs_itband', 'fs_plantar', 'fs_palmar', 'fs_galea',
  'fs_abdominal', 'fs_retinacula', 'fs_septa', 'fs_crural', 'fs_armfascia',
  'fs_pectoral', 'fs_cervical', 'fs_sheaths',
];
